# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "PowerTimer.xcworkspace",
      scheme: "PowerTimer",
      output_directory: "./fastlane/screenshots"
    )
  end

  lane :frame do
    frame_screenshots(white: true, path: "./fastlane/screenshots")
  end

  lane :release do
    screenshots
    frame
    build_app(
      clean: true,
      include_bitcode: true,
      workspace: "PowerTimer.xcworkspace",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_app_store
  end

  lane :update_metadata do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true
    )
  end
end
