# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

def create_and_push_tag(version, build_number)
  git_tag = "v#{version}.#{build_number}"
  if git_tag_exists(tag: git_tag)
    UI.error "Git tag `#{git_tag}` exists, cannot set version number."
    raise
  end
  commit_version_bump(message: "Version bump: #{git_tag}")
  add_git_tag(tag: git_tag)
  push_git_tags
end

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "PowerTimer.xcworkspace",
      scheme: "PowerTimer",
      output_directory: "./fastlane/screenshots",
      skip_open_summary: true,
      reinstall_app: true,
    )
  end

  lane :frame do
    frame_screenshots(white: true, path: "./fastlane/screenshots")
  end

  desc "Bump version number (type: [patch | minor | major])"
  desc "Example: `fastlane ios bump_version type:patch`"
  lane :bump_version do |options|
    version = increment_version_number(
      bump_type: options[:type] # without providing a type, defaults to 'patch'
    )

    # Reset build number to 0
    build_number = "0"
    increment_build_number(build_number: build_number)
    create_and_push_tag(version, build_number)
  end

  desc "Bump build number and create/push a new git tag"
  lane :bump_build_number do
    version = get_version_number
    build_number = increment_build_number
    create_and_push_tag(version, build_number)
  end

  lane :release do
    bump_build_number
    screenshots
    frame
    build_app(
      clean: true,
      include_bitcode: true,
      workspace: "PowerTimer.xcworkspace",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_app_store
  end

  lane :update_metadata do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true
    )
  end
end
